packages:
  # Core Tomoe packages
  - "packages/*"

  # Middleware Packages
  - "middleware/*"

  # Documentation and Examples
  - "apps/*"

  # Benchmarks (not part of main workspace)
  - "benchmarks"
